name: container
on: push
jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:18-alpine3.15
    steps: # all the steps will be run in the container instead of VM
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
