name: Link From docker action

on: push

jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          chmod 777 ./.github/actions/hello-docker/entrypoint.sh
      - uses: ./.github/actions/hello-docker
        id: hello
        with:
          who-to-greet: "World"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO